# Generated by Django 3.0.8 on 2020-07-27 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('activitytracking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Trivia_app.ActivityTracking')),
                ('name', models.CharField(max_length=500)),
                ('question', models.CharField(max_length=5000)),
                ('option1', models.CharField(max_length=5000)),
                ('option2', models.CharField(max_length=5000)),
                ('option3', models.CharField(max_length=5000)),
                ('option4', models.CharField(max_length=5000)),
                ('answer', models.CharField(max_length=5000)),
            ],
            bases=('Trivia_app.activitytracking',),
        ),
    ]
