# Generated by Django 3.0.8 on 2020-07-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='option4',
        ),
    ]
